### ISSUE TITLE
Wyszukiwanie na stronie głównej

### ISSUE THREAD

**Issue by mlazowik** [WarsawLO/warsawlo-2.0#22]
Czy przy obecnej nawigacji nie będzie tak, że >90% użytkowników będzie klikać CTA bez przeglądania tekstu poniżej?

**Comment by micorix** [comment]
@karoli-na myślę, że powinniśmy dodać też, pomimo wersji uproszczonej wyszukiwania, input z nazwą szkoły.

**Comment by karoli-na** [comment]
@micorix  I wtedy przy wyszukiwaniu po nazwie przenosi nas od razu do profilu konkretnej szkoły czy do listy szkół? Jeśli do konkretnego profilu, to musielibyśmy wtedy mieć pewnie podpowiedzi w dropdownie, bo wątpię, żeby każdy wpisywał pełną poprawną nazwę :)

**Comment by micorix** [comment]
Chyba na teraz najprościej byłoby do listy szkół
