### ISSUE TITLE
Metadane o szkole w tooltipie na mapie

### ISSUE THREAD

**Issue by mlazowik** [WarsawLO/warsawlo-2.0#23]
W tej chwili wyświetlamy tylko nazwę szkoły, można by dać więcej informacji typu profile, adres, być może link do sprawdzenia nawigacji w google/osm/jakdojadę? Konkretne elementy do ustalenia, na pewno nie chcemy przeładować tego widoku.

**Comment by micorix** [comment]
Częściowo zaimplementowane.

**Comment by micorix** [comment]
Enough for now
