### ISSUE TITLE
Chowające się filtry na widoku mapy

### ISSUE THREAD

**Issue by micorix** [WarsawLO/warsawlo-2.0#35]
Mapa obecnie zajmuje relatywnie mały obszar. Można by ją powiększyć chowając filtry.

Pytanie, jak to rozegrać UX-owo.

**Comment by karoli-na** [comment]
Zerknij, jak to się układa tutaj:  https://www.otodom.pl/sprzedaz/mieszkanie/warszawa/?search[region_id]=7&search[subregion_id]=197&search[city_id]=26&map=1 - mapa nie jest elementem, który zajmuje miejsce pozostałe do końca strony, tylko ma swoją wysokość i można przewinąć stronę do stopki.
Tak samo chociażby tutaj:
https://xd.adobe.com/spec/757bb86b-c6a3-454a-5cf2-34f910f4f603-034a/screen/44a27a6d-063f-4a9c-ac37-8c0149ac8ea9
Scrollujemy całą stronę, wysokość mapy nie jest zależna od ilości pustego miejsca. Tym samym, filtry się chowają i pokazuje się całość mapy. To chyba najłatwiejsze rozwiązanie :)
Żeby więcej mapy było widoczne od razu na 100% trzeba zmniejszyć wielkość nagłówka ( tutaj ta wartość 60 px to za dużo). Może 50 dla nagłówków na podstronach?

**Comment by micorix** [comment]
Kontynuacja dyskusji -> #54
