### ISSUE TITLE
Research on how to make Matomo GDPR compliant

### ISSUE THREAD

**Issue by micorix** [WarsawLO/warsawlo-2.0#43]

**Comment by eemila** [comment]
Matomo - steps to make it compliant with GDPR: 

1. List all the processed data (template on the drive - it can be done on go)
2. Add privacy note (mention about Matomo; right to access data, to withdraw consent, to erasure; lawful basis:  “Legitimate interest” or “Explicit consent”; collecting data from children - example: https://www.cognifit.com/pl/children-privacy-policy // I will write it - EG)
3. What if a user requests his data? - design the process of sharing the data with user
4. Cookies pop-up (I will write txt for this - EG)
5. Data breach procedure (I would need to deep dive here ;) - EG)

**Comment by mlazowik** [comment]
Do we need to do anything (apart from cookies -- that's separate from GDPR afaik)?

https://gdpr-info.eu/recitals/no-26/

**Comment by eemila** [comment]
Nope, actually I will take care of GDPR :) I wish we could start using Matomo soon

**Comment by micorix** [comment]
Handled internally
