### ISSUE TITLE
Pagination is hidden in grid view

### ISSUE THREAD

**Issue by micorix** [WarsawLO/warsawlo-2.0#45]

**Comment by eemila** [comment]
how about infinite scroll instead of pagination? :)

**Comment by micorix** [comment]
@eemila it's more like pure technical issue. Pagination existed before. I guess I removed it by accident. Should be easy to fix.

Talking more about design itself, I recall we agreed to use pagination because infinite scroll may be confusing when dealing with ordered data (e.g. user can't go back in history). But perhaps we should go back to that idea?

Just, please let me know if that type of change should be done before going on prod?
