### ISSUE TITLE
Replace grid search view with list view

### ISSUE THREAD

**Issue by micorix** [WarsawLO/warsawlo-2.0#55]
Reason for this change: school names are too long.

[mockups](https://xd.adobe.com/spec/757bb86b-c6a3-454a-5cf2-34f910f4f603-034a/screen/d4c97d07-e1c1-414b-8d5e-a1d56d28e6e8/)

![image](https://user-images.githubusercontent.com/20800459/99195581-e2da7280-2786-11eb-8dc7-630fc8ba885b.png)

**Comment by a-dabrowski** [comment]
Are there any views for mobile in portrait mode? Should be smaller on those smaller resolutions?

**Comment by micorix** [comment]
Hi @a-dabrowski! Thanks for joining the discussion :speech_balloon: .

![image](https://user-images.githubusercontent.com/20800459/99540799-4dbac200-29b0-11eb-9575-4f9dcd5e1908.png)

I believe this is mockup of the list view on mobile. In that case it wouldn't be much different comparing to what we have now. 

CCing @karoli-na . She's in charge of the design and can confirm it.

@a-dabrowski Do you want to implement this view? :slightly_smiling_face:

**Comment by karoli-na** [comment]
@micorix yest, it's more or less this view. It'll be modified a bit, since we need to add "heart" button here :)

**Comment by a-dabrowski** [comment]
If I can get `<REACT_APP_API_URL=<SERVER_URL>`, I could start it this week :)

**Comment by micorix** [comment]
Wow, great!

Yeah, sorry. We haven't updated the docs yet. Server URL is https://test.warsawlo.pl.

**Comment by a-dabrowski** [comment]
Here's PR for changing from grid to list, other things such as that heart button will be added in another PR

**Comment by micorix** [comment]
I believe #65 is connected to this issue.

**Comment by a-dabrowski** [comment]
Hey @micorix is there something else to be done on this issue or are we good to close it?

**Comment by micorix** [comment]
Yeah. Thanks @a-dabrowski.
